# 'bundle exec jekyll serve'

# Site variables
# in html: {{ site.title }}, {{ site.email }}, and so on.

title: tradingbot
owner: Jesse Frush
email: jesse.frush@gmail.com
linkedin_url: linkedin.com/in/jessefrush/
description: automate() the stock market
url: "https://turkycat.github.io"
baseurl: "/tradingbot"
twitter_username: turkycat
github_username:  turkycat
show_downloads: true
google_analytics:
#github: [metadata]
images: /images
logo: /images/logo.png
about: /about
css-path: /assets/css/style.css?v=

# jekyll build settings
remote_theme: turkycat/minimal
#theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-coffeescript

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

permalink: /:year/:month/:title

collections:
  bymonth:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
#      excerpt_separator: <!--preview-->
      start_exerpt: <!--start-->
      end_exerpt: <!--end-->      
  - scope:
      path: ""
      type: "bymonth"
    values:
#      layout: monthly
      layout: default
      permalink: /:title

# processing controls
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - minimal

include:
  - _layouts/
  - _posts/
  - _sass/
  - fonts/
  - images/
  - script/
  - about.md
  - index.md