# 'bundle exec jekyll serve'

# Site variables
# in html: {{ site.title }}, {{ site.email }}, and so on.

title: tradingbot
owner: Jesse Frush
email: jesse.frush@gmail.com
linkedin_url: linkedin.com/in/jessefrush/
description: >-
  &nbsp;  
  learn to automate a stock trader
baseurl: ""
url: "https://turkycat.github.io"
twitter_username: turkycat
github_username:  turkycat
show_downloads: true
google_analytics:
github: [metadata]
logo: /assets/images/logo.png

# jekyll build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# processing controls
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include: